name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up secret file
      env:
        SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        # DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD }}
        # DEBUG_SECRET_KEY: ${{ secrets.DEBUG_SECRET_KEY }}
      run: |
        echo "SURGE_DOMAIN=$SURGE_DOMAIN" > secrets.txt
        echo "SURGE_TOKEN=$SURGE_TOKEN" >> secrets.txt
#         echo $DEBUG_PASSWORD >> secrets.txt
#         echo $DEBUG_SECRET_KEY >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false